apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: {{ .Values.namespace }}
data:
  MYSQL_ROOT_USER: {{ .Values.db.root_username | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.db.root_password | b64enc | quote }}
  MYSQL_USER: {{ .Values.db.username | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.db.password | b64enc | quote }}
