apiVersion: v1
kind: Service
metadata:
  name: todo-nps
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: todo
  ports:
  - port: {{ .Values.app.target_port }}
    targetPort: {{ .Values.app.port }}
